server:
  servlet:
    context-path:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyan_mall_db?serverTimezone=UTC&
    username: root
    password: ss7832459

pagehelper:

      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

mybatis:
  type-handlers-package: com.cskaoyan.springboot.demo.util.String2ArrayHandler

  oss:
    bucket: cskaoyan
    endPoint: oss-cn-beijing.aliyuncs.com
    secretKey: LTAI8EgTxlc4QQZr
    secret: RBDvSGZOR8DaUJxlLrW4Ed46RVnAkR






