server:
  servlet:
    context-path: /admin
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall
    username: root
    password: 123456
