server:
  servlet:
    context-path: /admin
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 12345

mybatis:
  type-handlers-package: com.cskaoyan.springboot.demo.util.String2ArrayHandler